name: 🤖 Android Builds
on:
  workflow_call:

# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: master
  SCONSFLAGS: verbose=yes warnings=extra debug_symbols=no module_text_server_fb_enabled=yes

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-android
  cancel-in-progress: true

jobs:
  android-template:
    runs-on: "ubuntu-20.04"
    name: Template (target=${{ matrix.target }}, arch=${{ matrix.arch }})
    strategy:
      fail-fast: false
      matrix:
        target: [template_debug, template_release]
        arch: [arm32, arm64, x86_32, x86_64]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: android-template-${{ matrix.target }}-${{ matrix.arch }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} arch=${{ matrix.arch }}
          platform: android
          target: ${{ matrix.target }}
          tests: false

      - name: Make apk (template)
        run: |
          cd platform/android/java
          ./gradlew generateGodotTemplates
          cd ../../..
          
          mkdir -p templates

          mv bin/android_source.zip templates/android_source.zip || true
          mv bin/android_debug.apk templates/android_debug.apk || true
          mv bin/android_release.apk templates/android_release.apk || true

          rm -rf bin/*
          mv templates bin

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: android-template-${{ matrix.target }}-${{ matrix.arch }}
          path: bin/*
