name: 🍏 iOS Builds
on:
  workflow_call:

# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: master
  SCONSFLAGS: verbose=yes warnings=extra werror=yes debug_symbols=no module_text_server_fb_enabled=yes

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-ios
  cancel-in-progress: true

jobs:
  ios-template:
    runs-on: "macos-latest"
    name: Template (target=${{ matrix.target }}, arch=${{ matrix.arch }})
    strategy:
      fail-fast: false
      matrix:
        target: [template_debug, template_release]
        arch: [arm64, x86_64]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ios-template-${{ matrix.target }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} arch=${{ matrix.arch }}
          platform: ios
          target: ${{ matrix.target }}
          tests: false

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ios-template-${{ matrix.target }}
