name: 🍏 iOS Builds
on:
  workflow_call:

# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: master
  SCONSFLAGS: verbose=yes warnings=extra debug_symbols=no module_text_server_fb_enabled=yes

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-ios
  cancel-in-progress: true

jobs:
  ios-template:
    runs-on: "macos-latest"
    name: Template
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ios-template
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Compilation (target=template_debug)
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }}
          platform: ios
          target: template_debug
          tests: false

      - name: Compilation (target=template_release)
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }}
          platform: ios
          target: template_release
          tests: false

      - name: Make universal binaries and bundle (template)
        run: |
          cp -r misc/dist/ios_xcode bin

          strip bin/*.a

          mv bin/libgodot.ios.template_debug.arm64.a bin/ios_xcode/libgodot.ios.debug.xcframework/ios-arm64/libgodot.a
          mv bin/libgodot.ios.template_release.arm64.a bin/ios_xcode/libgodot.ios.release.xcframework/ios-arm64/libgodot.a

          cp -r ~/VulkanSDK/*/MoltenVK/MoltenVK.xcframework ios_xcode
          rm -rf ios_xcode/MoltenVK.xcframework/{macos,tvos}*
          mkdir bin/templates
          cd bin/ios_xcode
          zip -q -9 -r ../templates/ios.zip *
          cd ..
          rm -rf ios_xcode

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ios-template-${{ matrix.target }}-${{ matrix.arch }}
          path: bin/*
