name: 🍎 macOS Builds
on:
  workflow_call:

# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: master
  SCONSFLAGS: verbose=yes warnings=extra werror=yes module_text_server_fb_enabled=yes

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-macos
  cancel-in-progress: true

jobs:
  build-macos:
    runs-on: "macos-latest"
    name: ${{ matrix.name }} (target=${{ matrix.target }}, arch=${{ matrix.arch }})
    strategy:
      fail-fast: false
      matrix:
        target: [template_debug, template_release]
        include:
          - name: Template
            cache-name: macos-template
            sconsflags: debug_symbols=no
        exclude:
          - name: Editor
            cache-name: macos-editor
            target: editor
            arch: arm64

          - name: Editor
            cache-name: macos-editor
            target: editor
            arch: x86_64

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ${{ matrix.cache-name }}-${{ matrix.target }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Setup Vulkan SDK
        run: |
          sh misc/scripts/install_vulkan_sdk_macos.sh

      - name: Compilation (arm64)
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} arch=arm64
          platform: macos
          target: ${{ matrix.target }}
          tests: false

      - name: Compilation (x86_64)
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} arch=x86_64
          platform: macos
          target: ${{ matrix.target }}
          tests: false

      - name: Prepare artifact
        run: |
          strip bin/godot.*
          chmod +x bin/godot.*

      - name: Make universal binaries and bundle (editor)
        if: endsWith(matrix.cache-name, 'editor')
        run: |
          lipo -create bin/godot.macos.editor.x86_64 bin/godot.macos.editor.arm64 -output bin/godot.macos.editor.universal
          strip bin/godot.macos.editor.universal
          rm -rf bin/godot.macos.editor.x86_64 bin/godot.macos.editor.arm64
          cp -r misc/dist/macos_tools.app Godot.app
          mkdir Godot.app/Contents/MacOS
          cp bin/godot.macos.editor.universal Godot.app/Contents/MacOS/Godot
          chmod +x Godot.app/Contents/MacOS/Godot
          cp -n 'README.md' 'LICENSE' ${{ github.workspace }}/bin

      - name: Make universal binaries and bundle (template)
        if: endsWith(matrix.cache-name, 'template')
        run: |
          lipo -create bin/godot.macos.template_debug.x86_64 bin/godot.macos.template_debug.arm64 -output bin/godot.macos.template_debug.universal
          lipo -create bin/godot.macos.template_release.x86_64 bin/godot.macos.template_release.arm64 -output bin/godot.macos.template_release.universal
          rm -rf bin/godot.macos.template_debug.x86_64 bin/godot.macos.template_debug.arm64 bin/godot.macos.template_release.x86_64 bin/godot.macos.template_release.arm64
          strip bin/godot.*
          cp -r misc/dist/macos_template.app macos_template.app
          mkdir macos_template.app/Contents/MacOS
          cp bin/godot.macos.template_debug.universal macos_template.app/Contents/MacOS/godot_macos_debug.universal
          cp bin/godot.macos.template_release.universal macos_template.app/Contents/MacOS/godot_macos_release.universal
          chmod +x macos_template.app/Contents/MacOS/godot_macos_debug.universal
          chmod +x macos_template.app/Contents/MacOS/godot_macos_release.universal
          zip -r macos.zip macos_template.app
          rm -rf bin/*
          mkdir bin/templates
          mv macos.zip bin/template/macos.zip

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}-${{ matrix.target }}
