name: 🔄 Sync Fork
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  sync:
    name: "Sync"
    runs-on: ubuntu-latest
    steps:
      - name: Sync Fork with upstream
        uses: tgymnich/fork-sync@v1.8
        with:
          owner: godotengine
          repo: godot