name: 🌐 Web Builds
on:
  workflow_call:

# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: master
  SCONSFLAGS: verbose=yes warnings=extra werror=yes debug_symbols=no
  EM_VERSION: 3.1.18
  EM_CACHE_FOLDER: "emsdk-cache"

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-web
  cancel-in-progress: true

jobs:
  web-template:
    runs-on: "ubuntu-20.04"
    name: Template (target=${{ matrix.target }})
    strategy:
      fail-fast: false
      matrix:
        target: [template_debug, template_release]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Emscripten latest
        uses: mymindstorm/setup-emsdk@v12
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - name: Verify Emscripten setup
        run: |
          emcc -v

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: web-template-${{ matrix.target }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }}
          platform: web
          target: ${{ matrix.target }}
          tests: false

      - name: Prepare templates
        run: |
          mkdir -p templates

          mv bin/godot.web.template_release.wasm32.zip templates/web_release.zip || true
          mv bin/godot.web.template_release.wasm32.dlink.zip templates/web_dlink_release.zip || true
          mv bin/godot.web.template_debug.wasm32.zip templates/web_debug.zip || true
          mv bin/godot.web.template_debug.wasm32.dlink.zip templates/web_dlink_debug.zip || true

          rm -rf bin/*
          mv templates bin

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: web-template-${{ matrix.target }}
          path: bin/*
