name: 🏁 Windows Builds
on:
  workflow_call:

# Global Settings
# SCONS_CACHE for windows must be set in the build environment
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: master
  SCONSFLAGS: verbose=yes warnings=extra module_text_server_fb_enabled=yes
  SCONS_CACHE_MSVC_CONFIG: true

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows
  cancel-in-progress: true

jobs:
  build-windows:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }} (target=${{ matrix.target }}, arch=${{ matrix.arch }})
    strategy:
      fail-fast: false
      matrix:
        target: [template_debug, template_release]
        arch: [x86_32, x86_64]
        include:
          - name: Editor
            cache-name: windows-editor
            os: "windows-latest"
            target: editor
            arch: x86_64
            sconsflags: debug_symbols=no vsproj=yes windows_subsystem=console

          - name: Template
            cache-name: windows-template
            os: "ubuntu-20.04"
            sconsflags: debug_symbols=no

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ${{ matrix.cache-name }}-${{ matrix.target }}-${{ matrix.arch }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Install mingw64 (Linux)
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        shell: sh
        run: |
          sudo apt update
          sudo apt install gcc-multilib g++-multilib
          sudo apt-get install mingw-w64
          sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
          sudo update-alternatives --set i686-w64-mingw32-gcc /usr/bin/i686-w64-mingw32-gcc-posix
          sudo update-alternatives --set i686-w64-mingw32-g++ /usr/bin/i686-w64-mingw32-g++-posix

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }} arch=${{ matrix.arch }}
          platform: windows
          target: ${{ matrix.target }}
          tests: false

      - name: Prepare artifact
        run: |
          rm -rf bin/* -Include *.exp,*.lib,*.pdb -Force

      - name: Prepare templates
        if: endsWith(matrix.cache-name, 'template')
        shell: bash
        run: |
          mkdir -p templates

          mv bin/godot.windows.template_release.x86_64.exe bin/windows_release_x86_64.exe || true
          mv bin/godot.windows.template_debug.x86_64.exe bin/windows_debug_x86_64.exe || true
          mv bin/godot.windows.template_release.x86_32.exe bin/windows_release_x86_32.exe || true
          mv bin/godot.windows.template_debug.x86_32.exe bin/windows_debug_x86_32.exe || true
          
          mv bin/godot.windows.template_release.x86_64.console.exe bin/windows_release_x86_64_console.exe || true
          mv bin/godot.windows.template_debug.x86_64.console.exe bin/windows_debug_x86_64_console.exe || true
          mv bin/godot.windows.template_release.x86_32.console.exe bin/windows_release_x86_32_console.exe || true
          mv bin/godot.windows.template_debug.x86_32.console.exe bin/windows_debug_x86_32_console.exe || true

          rm -rf bin/*
          mv templates bin

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}-${{ matrix.target }}-${{ matrix.arch }}
          path: bin/*
