name: 🏁 Windows Builds
on:
  workflow_call:

# Global Settings
# SCONS_CACHE for windows must be set in the build environment
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: master
  SCONSFLAGS: verbose=yes warnings=extra werror=yes module_text_server_fb_enabled=yes
  SCONS_CACHE_MSVC_CONFIG: true

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows
  cancel-in-progress: true

jobs:
  build-windows:
    # Windows 10 with latest image
    runs-on: "windows-latest"
    name: ${{ matrix.name }} (target=${{ matrix.target }}, arch=${{ matrix.arch }})
    strategy:
      fail-fast: false
      matrix:
        target: [editor, template_debug, template_release]
        arch: [x86_32, x86_64]
        include:
          - name: Editor
            cache-name: windows-editor
            sconsflags: debug_symbols=no vsproj=yes windows_subsystem=console

          - name: Template
            cache-name: windows-template
            sconsflags: debug_symbols=no

    steps:
      - uses: actions/checkout@v3

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ${{ matrix.cache-name }}-${{ matrix.target }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Setup MSVC problem matcher
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }} arch=${{ matrix.arch }}
          platform: windows
          target: ${{ matrix.target }}
          tests: false

      - name: Prepare artifact
        run: |
          Remove-Item bin/* -Include *.exp,*.lib,*.pdb -Force

      - name: Prepare templates
        if: endsWith(matrix.cache-name, 'template')
        shell: bash
        run: |
          mkdir -p templates

          mv bin/godot.windows.template_release.x86_64.exe bin/windows_release_x86_64.exe || true
          mv bin/godot.windows.template_debug.x86_64.exe bin/windows_debug_x86_64.exe || true
          mv bin/godot.windows.template_release.x86_32.exe bin/windows_release_x86_32.exe || true
          mv bin/godot.windows.template_debug.x86_32.exe bin/windows_debug_x86_32.exe || true
          
          mv bin/godot.windows.template_release.x86_64.console.exe bin/windows_release_x86_64_console.exe || true
          mv bin/godot.windows.template_debug.x86_64.console.exe bin/windows_debug_x86_64_console.exe || true
          mv bin/godot.windows.template_release.x86_32.console.exe bin/windows_release_x86_32_console.exe || true
          mv bin/godot.windows.template_debug.x86_32.console.exe bin/windows_debug_x86_32_console.exe || true

          rm -rf bin/*
          mv templates bin

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}-${{ matrix.target }}
          path: bin/*
